// <auto-generated />
namespace DraftHits.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _27_03_2015_00 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27_03_2015_00));
        
        string IMigrationMetadata.Id
        {
            get { return "201503270533536_27_03_2015_00"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
